### ISSUE TITLE
Macro get_creative_history_columns outdated

### ISSUE THREAD

**Issue by felipecoxanet** [fivetran/dbt_linkedin_source#50]
Hi, in January some columns was changed in the table **creative_history**, can I open a PR to fix the macro **get_creative_history_columns** or you alread have plans to fix it?

Fivetran DOC listin the new columns:
https://fivetran.com/docs/applications/linkedin-ads/changelog

Macro code: https://github.com/fivetran/dbt_linkedin_source/blob/6b1ef6910d8b03dd1ebc50fbbd3e98ee90d725d4/macros/get_creative_history_columns.sql

Column affected:
`call_to_action_label_type` to `call_to_action`
`created_time` to `created_at`
`last_modified_time` to `last_modified_at`
`status` to `intended_status`
`type` --was excluded
`version_tag` --was excluded

**Comment by fivetran-joemarkiewicz** [comment]
Hi @felipecoxanet thanks for raising this issue. We are currently working on this update within [dbt_linkedin PR#27](https://github.com/fivetran/dbt_linkedin/issues/27). We are planning to have this update out by the end of the week.

I will post back here once these updates are live to account for the API changes.

**Comment by fivetran-joemarkiewicz** [comment]
HI @felipecoxanet I wanted to post back and let you know that the latest releases of the linkedin ads dbt package should resolve the issue you identified above. You should be able to upgrade and see the issue resolved.

As such, I will close this issue. However, please feel free to reopen if the issue persists.
